      pipeline {
        agent {label 'sonarqube'}
        stages {
          stage("build & SonarQube analysis") {
            agent {label 'sonarqube'}
            steps {
              withSonarQubeEnv('SonarScanner') {
                    dir("/CICD/JenkinsWar") {  
                sh 'mvn clean package sonar:sonar'
                }
              }
            }
          }
          stage("Quality Gate") {
            steps {
              timeout(time: 1, unit: 'HOURS') {
                waitForQualityGate abortPipeline: true
              }
            }
          }
        }
      }
