      pipeline {
        agent {label 'georgeJavaNode01'}
        stages {
          stage("build & SonarQube analysis") {
            agent {label 'georgeJavaNode01'}
            steps {
              withSonarQubeEnv('SonarScanner') {
                    dir("/root/workspace/Sonarqube-pipeline/JenkinsWar") { 
                sh '''
                      mvn clean package sonar:sonar
                   '''
                }
              }
            }
          }
         }
       }

