      pipeline {
        agent {label 'sonarqube'}
        stages {
          stage("build & SonarQube analysis") {
            steps {
              withSonarQubeEnv('SonarScanner') {
                    dir("/CICD/JenkinsWar") {  
                sh 'mvn clean package sonar:sonar'
                }
              }
            }
          }
         }
       }

