apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapp
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: javaapp
  template:
    metadata:
      labels:
        app: javaapp
    spec:
      containers:
      - image: docker.io/georgechiu/cicd
        name: javaapp
        ports:
        - containerPort: 8080
