---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: javaapp
  name: javaapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javaapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: javaapp
    spec:
      containers:
      - image: quay.online.ocp4.com/admin/cicd
        name: javaapp
        env:
        - name: COLOR
          value: "blue"
        resources: {}
---
